M48
; DRILL file {KiCad 9.0.3} date 2025-07-14T03:19:36-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-14T03:19:36-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.300
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T3C7.000
%
G90
G05
T1
X145.3Y-94.0
X145.3Y-103.1
X146.3Y-92.6
T3
X169.7Y-60.1
T2
G00X153.356Y-108.635
M15
G01X153.356Y-108.635
M16
G05
M30
